import Head from "next/head";
import { Content3Col, Footer, HomeBanner, Parcerias, TextCol } from "@impulsogov/design-system";
import { InfoTab } from "../components/InfoTab";

const homeBannerProps = {
  title: 'Indicadores de Saúde Mental',
  text: 'Aqui você pode acompanhar de forma descomplicada a situação da RAPS e demais serviços de saúde mental de Aracaju (SE). Por meio de dados e indicadores, monitore a qualidade do cuidado prestado e aprofunde seu diagnóstico sobre o território e a população atendida.'
}

const infoTabprops = [
  {
    leftTitle: "Saúde Mental",
    rightTitle: "O que é a plataforma de indicadores de Saúde Mental?",
    rightContent: "Uma plataforma gratuita, que utiliza bases de dados públicas para auxiliar na gestão dos serviços de saúde mental do município. Conheça mais sobre o trabalho realizado pela Impulso em parceria com o Instituto Cactus e o município de Aracaju (SE).",
    buttonTitle: "SOBRE SAÚDE MENTAL",
    onClick: () => console.log("primeiro botão")
  },
  {
    leftTitle: "Glossário",
    rightTitle: "Entenda como interpretar os indicadores",
    rightContent: "Acesse um siglário e a ficha técnica de nossos indicadores para compreender como eles são calculados, quais são as bases de dados que os alimentam, com qual periodicidade eles são atualizados e muito mais",
    buttonTitle: "entenda",
    onClick: () => console.log("segundo botão")
  },
];

const parceiros = [{ alt: "parceiros", src: "https://media.graphassets.com/ekDlCVRsRQuxlx6F5KUK" }, { alt: "parceiros", src: "https://media.graphassets.com/ekDlCVRsRQuxlx6F5KUK" }, { alt: "parceiros", src: "https://media.graphassets.com/ekDlCVRsRQuxlx6F5KUK" }]


export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ backgroundColor: "#1B2D82" }}>


        <HomeBanner
          titulo={homeBannerProps.title} texto={homeBannerProps.text} theme="ColorSM"
        />
        <Content3Col
          titulo="Por que devo fazer?"
          child1={
            <TextCol
              titulo="Descomplicada"
              corpo="Você preenche um formulário, nós entramos em contato em até três dias úteis e já marcamos a primeira conversa. Não precisa assinar nada, é sem burocracia."
            />
          }
          child2={
            <TextCol
              titulo="Gratuita"
              corpo="A consultoria é 100% gratuita. Você poderá marcar até três encontros totalmente gratuitos e ter acesso a análises e materiais criados por nossos especialistas."
            />
          }
          child3={
            <TextCol
              titulo="Personalizada"
              corpo="Trazemos análises e recomendações personalizadas para seu município melhorar nos indicadores e na capitação ponderada, sempre adequando à realidade local."
            />
          }
        />
        <section id="sobre">
          <InfoTab contentList={infoTabprops} />
        </section>



        <Parcerias
          parceiros={parceiros}
          theme="ColorAGP"
        />
      </div>
      <Footer
        contactCopyright={{
          email: "contato@impulsogov.org",
          copyright: "© 2021 Impulso"
        }}
        theme={{
          logoProjeto: "https://media.graphassets.com/Kal4aulRmYkqd0L6RBAd",
          cor: "Black"
        }}
        menu={
          [
            { label: "A Impulso Gov", url: "/impulsogov" },
            { label: "O Previne Brasil", url: "/previnebrasil" },
            { label: "Análise", url: "" },
            { label: "Consultoria", url: "/consultoria" }
          ]
        }
        subtitles={[
          { label: "Indicadores de Desempenho", url: "/indicadores" },
          { label: "Capitação Ponderada", url: "/capitacao" },
          { label: "Ações Estratégicas", url: "/acoes-estrategicas" },
        ]}
        links={[
          {
            label: "Sobre", url: "/sobre"
          },
          {
            label: "Competências e Soluções", url: "/competencias"
          }
        ]}

        address={{
          first: "Rua Aracaju 100 - Vila Madalena,",
          second: "São Paulo - SP, 01010-100"
        }}

        socialMediaURLs={[
          {
            url: "http://instagran.com",
            logo: ""
          }
        ]}
      />
    </>
  )
}
